spring:
  jackson:
      serialization:
        WRITE_DATES_AS_TIMESTAMPS: false
  datasource: 
      driverClassName: com.mysql.jdbc.Driver 
      url: jdbc:mysql://127.0.0.1:3306/hibernateuserdb?autoReconnect=true&useUnicode=true&characterEncoding=utf8&verifyServerCertificate=false&useSSL=false
      username: hibernateUser
      password: hibernateUser
  jpa:    
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true


logging:
  level:
    org.springframework.security: DEBUG
    org:
      hibernate:
        type: trace


facebook:
  client:
    clientId: 1236360259835060
    clientSecret: a29e111e887908acefa6e473142b185e
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me?fields=id, name, email, picture

google :
  client :
    clientId : 543176872858-43kgsap7ro6f5s6qasr0046727ddbub9.apps.googleusercontent.com
    clientSecret: 8l-D-egv7yOWEjsXIn18wCQF
    accessTokenUri: https://www.googleapis.com/oauth2/v4/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
    clientAuthenticationScheme: form
    scope:
    - email
    - profile
  resource:
    userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo

server:
  port: 8443
  ssl:
    key-store: C:/Users/jcmlo/keystore.p12
    key-store-password: wncjfals1
    keyStoreType: PKCS12
    keyAlias: tomcat